#!/usr/bin/env bash

set -e

# variables --------------------------------------------------------------------

name="cdok"
c_version="gnu23"

root="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$root"

current_date=$(date +"%F")

latest_git_commit=$(git log -1 --format='%ad' --date=format:'%d %b %Y')
if git rev-parse --is-inside-work-tree > /dev/null 2>&1; then
    git_head_hash_short=$(git rev-parse --short HEAD)
    git_head_hash_long=$(git rev-parse HEAD)
else
    git_head_hash_short="nogit"
    git_head_hash_long="0.0.0"
fi

get_version() {
    git describe --tags --abbrev=0 2>/dev/null || echo "v0.1.0"
}
VERSION="$(get_version)"

# build ------------------------------------------------------------------------

c_flags_test=(
    "-std=$c_version" "-g" "-O0" "-DDEBUG" "-fsanitize=address"
    "-Wall" "-Wextra" "-Wpedantic" "-Wshadow" "-Werror=format-security"
)

c_flags_debug=(
    "-std=$c_version" "-g" "-O0" "-DDEBUG" "-fsanitize=address" "-Wall"
    "-Wextra" "-Wpedantic" "-Wshadow" "-Werror=format-security"
)

c_flags_release=(
    "-O2" "-DNDEBUG" "-Wextra"
)

# arguments --------------------------------------------------------------------

debug_dir="$root/build/debug"
mkdir -p $debug_dir
build_debug() {
    IFS=" "
    cd $root/tools/nob/; cc nob.c -o nob
    c_flags="${c_flags_debug[*]}"
    ./nob "$root/src" $c_flags

    bin_name=$name-$VERSION-debug-$git_head_hash_short
    mv main $debug_dir/$bin_name
    cd $root
    rm -rf $root/gen; mkdir -p $root/gen
    $debug_dir/$bin_name -s $root/src -d $root/gen -o
}

if [ -z "$1" ]; then
    # if no arguments
  build_debug
else
  case "$1" in
    release)
        build_release
      ;;
    debug)
      build_debug
      ;;
    test)
      build_test
      ;;
    *)
      echo "Error: unknown argument '$1'"
      exit 1
      ;;
  esac
fi


