#!/usr/bin/env bash

set -xe

# variables --------------------------------------------------------------------

name="cdok"
c_version="gnu23"

root="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$root"

# build ------------------------------------------------------------------------

c_flags_test=(
    "-std=$c_version"
    "-g"
    "-O0"
    "-DDEBUG"
    "-fsanitize=address"
    "-Wall"
    "-Wextra"
    "-Wpedantic"
    "-Wshadow"
    "-Werror=format-security"
)

c_flags_debug=(
    "-std=$c_version"
    "-g"
    "-O0"
    "-DDEBUG"
    "-fsanitize=address"
    "-Wall"
    "-Wextra"
    "-Wpedantic"
    "-Wshadow"
    "-Werror=format-security"
)

c_flags_release=(
    "-O2"
    "-DNDEBUG"
    "-Wextra"
)

cd $root/tools/nob/
cc nob.c -o nob

IFS=" "

c_flags="${c_flags_test[*]}"
./nob "$root/src" $c_flags

current_date=$(date +"%F")

latest_git_commit=$(git log -1 --format='%ad' --date=format:'%d %b %Y')
if git rev-parse --is-inside-work-tree > /dev/null 2>&1; then
    git_head_hash_short=$(git rev-parse --short HEAD)
    git_head_hash_long=$(git rev-parse HEAD)
else
    git_head_hash_short="nogit"
    git_head_hash_long="0.0.0"
fi

get_version() {
    git describe --tags --abbrev=0 2>/dev/null || echo "v0.1.0"
}
VERSION="$(get_version)"

mkdir -p $root/build
bin_name=$name-$VERSION-test-$git_head_hash_short
mv main $root/build/$bin_name

# launch -----------------------------------------------------------------------

cd $root
mkdir gen
./build/$bin_name -s ./src -d ./gen

