#ifndef FILE_CONTENT_H
#define FILE_CONTENT_H

static const char table_start[] = "        <table>\n"
                                  "            <thead>\n"
                                  "                <tr>\n"
                                  "                    <th>id</th>\n"
                                  "                    <th>path</th>\n"
                                  "                    <th>name</th>\n"
                                  "                    <th>type</th>\n"
                                  "                    <th>header</th>\n"
                                  "                    <th>tags</th>\n"
                                  "                </tr>\n"
                                  "            </thead>\n"
                                  "            <tbody>\n";

static const char main_header_content[] =
    "<header>\n"
    "    <div class=\"header-search\">\n"
    "        <p>search: 's' or '/'</p>\n"
    "        <input\n"
    "                id=\"search\"\n"
    "                type=\"search\"\n"
    "                placeholder=\"id, path, type, name, description...\"\n"
    "                autocomplete=\"off\"\n"
    "                >\n"
    "    </div>\n";

static const char footer_content[] =
    "<footer>\n"
    "<script>\n"
    "    document.addEventListener(\"DOMContentLoaded\", () => {\n"
    "        const search = document.querySelector(\"#search\");\n"
    "        const tbody = document.querySelector(\"tbody\");\n"
    "\n"
    "        if (!search) return;\n"
    "\n"
    // "    window.history.scrollRestoration = \" manual \";\n"
    // "indow.scrollTo(0, 0);\n"

    "        const onIndexPage = "
    "window.location.pathname.endsWith(\"index.html\") ||\n"
    "            window.location.pathname.endsWith(\"/\");\n"

    "\n"
    "        if (onIndexPage) {\n"
    "    search.focus({ preventScroll: true });\n"
    "            search.focus();\n"
    "            search.select();\n"
    "            window.scrollTo(0,0);\n"
    "        }\n"
    "\n"
    "        search.addEventListener(\"focus\", () => {\n"
    "            if (!onIndexPage) {\n"
    "                window.location.href = \"index.html#search\";\n"
    "            }\n"
    "        });\n"
    "\n"

    "        document.addEventListener(\"keydown\", event => {\n"
    "            const active = document.activeElement;\n"
    "            const isTyping = active && (\n"
    "                active.tagName === \"INPUT\" ||\n"
    "                active.tagName === \"TEXTAREA\" ||\n"
    "                active.isContentEditable\n"
    "            );\n"
    "\n"
    "            if (!isTyping && (event.key === \"s\" ||\n"
    "                event.key === \"/\")) {\n"
    "                event.preventDefault();\n"
    "\n"
    "                if (onIndexPage) {\n"
    "                    search.focus();\n"
    "                    search.select();\n"
    "                } else {\n"
    "                    window.location.href = \"index.html#search\";\n"
    "                }\n"
    "            }\n"
    "        });\n"
    "\n"
    "        if (!tbody) return;\n"
    "\n"
    "        const rows = [...tbody.querySelectorAll(\"tr\")];\n"

    "\n"
    "        for (const row of rows) {\n"
    "            row.tabIndex = 0;\n"
    "\n"
    "            row.addEventListener(\"keydown\", event => {\n"
    "                if (event.key === \"Enter\") {\n"
    "                    event.preventDefault();\n"
    "                    row.click();\n"
    "                }\n"
    "            });\n"
    "        }\n"
    "\n"
    "        /* id, path, name, header */\n"
    "        const searchableColumns = [0, 1, 3, 2, 4, 5];\n"
    "\n"
    "        function getSections() {\n"
    "            const sections = [];\n"
    "            let currentSection = null;\n"

    "\n"
    "            for (const row of rows) {\n"
    "                if (row.classList.contains(\"file-section\")) {\n"
    "                    currentSection = {\n"
    "                        header: row,\n"
    "                        rows: []\n"
    "                    };\n"
    "                    sections.push(currentSection);\n"
    "                } else if (currentSection) {\n"
    "                    currentSection.rows.push(row);\n"
    "                }\n"
    "            }\n"
    "\n"
    "            return sections;\n"
    "        }\n"
    "\n"
    "        function rowMatches(row, query) {\n"
    "            const cells = [...row.children];\n"

    "\n"
    "            return searchableColumns.some(index => {\n"
    "                return cells[index]?.textContent\n"
    "                    .toLowerCase().includes(query);\n"
    "            });\n"
    "        }\n"
    "\n"
    "        function updateSearch() {\n"
    "            const query = search.value.trim().toLowerCase();\n"
    "            const sections = getSections();\n"

    "\n"
    "            for (const section of sections) {\n"
    "                let hasVisibleRows = false;\n"
    "\n"
    "                for (const row of section.rows) {\n"
    "                    const matches = query === \"\" ||\n"
    "                        rowMatches(row, query);\n"
    "\n"
    "                    row.hidden = !matches;\n"
    "                    row.tabIndex = matches ? 0 : -1;\n"
    "\n"
    "                    if (matches) {\n"
    "                        hasVisibleRows = true;\n"
    "                    }\n"
    "                }\n"
    "\n"
    "                section.header.hidden = query !== \"\" &&\n"
    "                    !hasVisibleRows;\n"
    "                section.header.tabIndex = section.header.hidden ? -1 : "
    "0;\n"
    "            }\n"
    "        }\n"
    "\n"

    "        search.addEventListener(\"input\", updateSearch);\n"
    "\n"
    "    });\n"
    "</script>\n"
    "<script "
    "src=\"https://cdn.jsdelivr.net/npm/prismjs/prism.js\"></script>\n"
    "<script "
    "src=\"https://cdn.jsdelivr.net/npm/prismjs/components/"
    "prism-c.min.js\">"
    "</script>\n"
    "</footer>\n";

static const char header_content[] =
    "<!DOCTYPE html>"
    "<html lang=\"en\">"
    "<head>"
    "<style>"
    "@font-face {\n"
    "    font-family: 'maple';\n"
    "    src: url('static/MapleMono.ttf') format('truetype'),\n"
    "    font-weight: 400;\n"
    "    font-style: normal;\n"
    "    font-display: swap;\n"
    "}\n"
    "\n"
    ":root {\n"
    "    --fg_1:  #AAB3C0;\n"
    "    --fg_2: #6e6e87;\n"
    "    --mg_1: #40404f;\n"
    "    --bg_1: #2a2a33;\n"
    "    --bg_2: #25252d;\n"
    "    --acc_1: #E7B589;\n"
    "    --acc_2: #ABABCE;\n"
    "    --acc_3: #C48283;\n"
    "}\n"
    "html,body {\n"
    "    font-family: \"maple\", monospace !important;\n"
    "    color: var(--fg_1);\n"
    "    background:var(--bg_2);\n"
    "}\n"
    "    .item-nametype {\n"
    "    display: inline-flex;\n"
    "    gap: 10px;\n"
    "}\n"
    "\n"
    "/* Basic table styling */\n"
    "table {\n"
    "    width: 100%;\n"
    "    border-collapse: collapse;\n"
    "    margin: 10px 10px 10px 0px;\n"
    "    font-size: 14px;\n"
    "    text-align: left;\n"
    "}\n"
    "\n"
    "/* Table header */\n"
    "th {\n"
    "    background-color: var(--mg_1);\n"
    "    color: var(--fg_1);\n"
    "    padding: 10px;\n"
    "}\n"
    "\n"
    "/* id field */\n"
    "th:nth-child(1),\n"
    "td:nth-child(1) {\n"
    "    width: 40px;\n"
    "    max-width: 40px;\n"
    "}\n"
    "\n"
    "/* name field */\n"
    "th:nth-child(3),\n"
    "td:nth-child(3) {\n"
    "    width: 20%;\n"
    "    max-width: 20%;\n"
    "}\n"
    "/* type field */\n"
    "th:nth-child(4),\n"
    "td:nth-child(4) {\n"
    "    width: 10%;\n"
    "    max-width: 10%;\n"
    "}\n"
    "\n"
    "/* path field */\n"
    "th:nth-child(2),\n"
    "td:nth-child(2) {\n"
    "    display: none;\n"
    "}\n"
    "\n"
    "/* tags field */\n"
    "th:nth-child(6),\n"
    "td:nth-child(6) {\n"
    "    width: 30%;\n"
    "    max-width: 30%;\n"
    "}\n"
    "\n"
    ".file-section>* {\n"
    "    text-align: left;\n"
    "    background-color: var(--bg_1);\n"
    "    color: var(--acc_1);\n"
    "    font-size: 16px;\n"
    "    border-bottom: 3px solid var(--fg_2);\n"
    "}\n"

    "\n"
    "/* Table cells */\n"
    "td {\n"
    "    padding: 10px;\n"
    "    color: var(--fg_1);\n"
    "    border-bottom: 1px solid var(--fg_2);\n"
    "}\n"
    "\n"
    "/* Hover effect */\n"
    "tr:hover {\n"
    "    background-color: var(--bg_1);\n"
    "    color: var(--fg_1);\n"
    "    <!-- cursor: pointer; -->\n"
    "}\n"
    "/* Optional: border around table */\n"
    "table, th, td {\n"
    "    border: 1px solid var(--fg_2);\n"
    "}\n"

    "header {\n"
    "    display: flex;\n"
    "    justify-content: space-between;\n"
    "    align-items: center;\n"
    "    margin: 0;\n"
    "    padding: 0;\n"
    "    padding-bottom: 4px;\n"
    "}\n"
    ".header-search {\n"
    "    justify-content: space-between;\n"
    "    align-items: center;\n"
    "}\n"
    "hr {\n"
    "    color: var(--mg_1);\n"
    "}\n"

    "input {\n"
    "    background-color: var(--mg_1);\n"
    "    padding: 8px;\n"
    "    width: 400px;\n"
    "    border: none;\n"
    "    color: var(--acc_1);\n"
    "    font-family: \"maple\", monospace !important;\n"
    "    border: 1px solid var(--fg_2);\n"
    "    /* border-radius: 10px; */\n"
    "}\n"
    "input::placeholder {\n"
    "    color: var(--fg_2);\n"
    "\n"
    "}\n"
    "\n"
    ".header-right {\n"
    "    margin-left: auto;\n"
    "    text-align: right;\n"
    "    justify-content: space-between;\n"
    "    align-items: center;\n"
    "}\n"

    ".header-right a{\n"
    "    color: var(--acc_1);\n"
    "}\n"
    "p, a {\n"
    "    color: var(--fg_1);\n"
    "}\n"
    "\n"
    "/* ========= item page ========= */\n"
    "\n"
    ".item-name {\n"
    "    color: var(--acc_2);\n"
    "}\n"
    ".item-type {\n"
    "    color: var(--acc_3);\n"
    "\n"

    "}\n"
    ".item-code, code {\n"
    "    background-color: var(--bg_1);\n"
    "}\n"
    "code {\n"
    "    background-color: var(--bg_1) !important;\n"
    "    font-size: 16px;\n"
    "    display: inline-block;\n"
    "        padding: 20px 20px;\n"
    "\n"

    "}\n"
    "pre[class*=\"language-\"] {\n"
    "  background: none !important;\n"
    "  width: 100%;\n"
    "  box-shadow: 0;\n"
    "  border: none !important;\n"
    "  padding: 0; /* optional */\n"
    "  text-shadow: none !important;\n"
    "}\n"
    "/*.token.variable{ color: #fff; }*/\n"
    ".token {\n"
    "  background: none !important;\n"
    "}\n"
    "\n"

    "code[class*=\"language-\"] {\n"
    " /* color: var(--fg_1) !important;*/\n"
    "  background: var(--bg_1) !important;\n"
    "  text-decoration: none !important;\n"
    "  text-shadow: none !important;\n"
    "}\n"
    ".item-tags {\n"
    "        color: var(--acc_1);\n"
    "\n"
    "}\n"
    ".item-desc {\n"
    "        color: var(--acc_2);\n"
    "}\n"
    ".token.comment { color: var(--fg_2) !important; }\n"
    ".token.keyword { color: var(--acc_1) !important; }\n"
    ".token.string  { color: var(--acc_2) !important; }\n"
    ".token.number  { color: #f38ba8 !important; }\n"
    ".token.function { color: var(--acc_3) !important; }\n"

    ".token.operator,\n"
    ".token.punctuation {\n"
    "color: var(--fg_1) !important;\n"
    "}\n"
    "    tr:focus {\n"
    "    outline: 2px solid var(--acc_1);\n"
    "    background-color: var(--bg_1);\n"
    "}\n"
    "</style>\n"
    "</head>";

#endif
